# Generated by Django 2.2.5 on 2019-09-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
