# Generated by Django 2.2.5 on 2019-09-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
