# Generated by Django 2.2.5 on 2019-09-28 09:38

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=store.models.upload_image_item),
        ),
    ]
