# Generated by Django 2.2.5 on 2019-10-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_сheckout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Сheckout',
        ),
    ]
